# Generated by Django 3.2.5 on 2021-07-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='orderid',
            new_name='order_id',
        ),
    ]
